import type {
  Currency,
  Wallet,
  Transaction,
} from "./types";

export const currencies: Currency[] = [
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "BTC", name: "Bitcoin", symbol: "₿" },
];

export const initialWallets: Wallet[] = [
  {
    id: "w1",
    currency: currencies[0],
    balance: 12500.0,
    name: "Primary USD Account",
  },
  {
    id: "w2",
    currency: currencies[1],
    balance: 8000.0,
    name: "Vacation Fund (EUR)",
  },
  { id: "w3", currency: currencies[4], balance: 2.5, name: "Crypto Holdings" },
];

export const initialTransactions: Transaction[] = [
  {
    id: "t1",
    date: new Date("2024-07-20T10:00:00Z"),
    walletId: "w1",
    type: "Deposit",
    amount: 500,
    status: "Completed",
    description: "Salary deposit",
  },
  {
    id: "t2",
    date: new Date("2024-07-19T14:30:00Z"),
    walletId: "w2",
    type: "Transfer",
    amount: -200,
    status: "Completed",
    description: "Sent to John Doe",
  },
  {
    id: "t3",
    date: new Date("2024-07-18T09:00:00Z"),
    walletId: "w3",
    type: "Swap",
    amount: 0.1,
    status: "Completed",
    description: "Swapped USD for BTC",
  },
  {
    id: "t4",
    date: new Date("2024-07-17T18:45:00Z"),
    walletId: "w1",
    type: "Withdrawal",
    amount: -150,
    status: "Completed",
    description: "ATM withdrawal",
  },
  {
    id: "t5",
    date: new Date("2024-07-16T11:20:00Z"),
    walletId: "w2",
    type: "Deposit",
    amount: 1000,
    status: "Completed",
    description: "Project payment",
  },
  {
    id: "t6",
    date: new Date("2024-07-15T16:00:00Z"),
    walletId: "w1",
    type: "Transfer",
    amount: -300,
    status: "Pending",
    description: "Payment to utility company",
  },
  {
    id: "t7",
    date: new Date("2024-07-14T12:00:00Z"),
    walletId: "w1",
    type: "Deposit",
    amount: 2000,
    status: "Completed",
    description: "Client payment",
  },
  {
    id: "t8",
    date: new Date("2024-07-13T15:20:00Z"),
    walletId: "w2",
    type: "Withdrawal",
    amount: -50,
    status: "Completed",
    description: "Coffee shop",
  },
  {
    id: "t9",
    date: new Date("2024-07-12T08:00:00Z"),
    walletId: "w3",
    type: "Deposit",
    amount: 0.5,
    status: "Completed",
    description: "BTC purchase",
  },
  {
    id: "t10",
    date: new Date("2024-07-11T20:00:00Z"),
    walletId: "w1",
    type: "Transfer",
    amount: -500,
    status: "Failed",
    description: "Rent payment (failed)",
  },
  {
    id: "t11",
    date: new Date("2024-07-10T13:45:00Z"),
    walletId: "w2",
    type: "Deposit",
    amount: 300,
    status: "Completed",
    description: "Refund from online store",
  },
];
